const assert=require('node:assert/strict');
const R=require('./chapter2-v3-state');
const {drain,work,wind,manuscript}=require('./chapter2-test-helpers.cjs');
const act=(s,type,target,value)=>drain(R.act(s,{type,target,value}));
let s=drain(R.initial());
s=act(s,'answer','dew','이슬');assert.equal(s.answers.dew,undefined);
s=act(s,'inspect','leaves');s=act(s,'answer','dew','이슬');assert.equal(s.answers.dew,undefined);
s=act(s,'inspect','weather-record');s=act(s,'inspect','leaves');
s=act(s,'answer','dew','비');assert.equal(s.answers.dew,undefined);
s=act(s,'answer','dew',' 이슬 ');assert.equal(s.answers.dew,true);
assert.equal(R.initial(JSON.parse(JSON.stringify(s))).answers.dew,true);
for(const [id,answer] of [['sky','구름'],['fog','안개']]){s=act(s,'inspect',id);s=act(s,'answer',id,answer);}
assert.equal(s.room,'yard','카메라 메모 없이 이동 금지');
s=R.act(s,{type:'inspect',target:'camera'});assert.equal(s.room,'yard','마지막 단서 대사를 읽어야 이동');
s=drain(s);assert.equal(s.room,'prep');
s=act(s,'use','recorder');assert.equal(s.complete,false);
s=act(s,'inspect','ribbon');s=act(s,'answer','wind','왼쪽');assert.equal(s.answers.wind,undefined);
s=act(s,'answer','wind-evidence','서풍');assert.equal(s.answers.wind,true);
s=act(s,'inspect','ruler');s=act(s,'select','ruler');s=act(s,'inspect','paper');assert.equal(s.seen.recovered,true);
s=act(s,'inspect','clip');s=act(s,'select','clip');s=act(s,'inspect','paper');assert.equal(s.seen.secured,true);
s=act(s,'inspect','strap');assert.ok(!s.seen.doorOpen);
s.answers['lab-mass']=true;s.answers['lab-breeze']=true;
s=act(s,'inspect','tape');s=work(s,manuscript);s=act(s,'select','tape');s=act(s,'inspect','recorder');assert.equal(s.seen.inserted,true);
s=act(s,'operate','play');assert.equal(s.complete,false,'되감기 먼저');
s=act(s,'operate','rewind');s=R.act(s,{type:'operate',target:'play'});assert.equal(s.complete,false,'결말 대사 먼저');
s=drain(s);assert.equal(s.complete,false);assert.equal(s.room,'archive');assert.equal(s.seen.doorOpen,true);
s=act(s,'inspect','photos');assert.equal(s.question,'','일지와 약도 확인 전 추측 확정 금지');
s=act(s,'inspect','logbook');s=act(s,'inspect','map');s=act(s,'inspect','photos');
assert.equal(s.question,'photo');
s=act(s,'evidence','fog');s=act(s,'evidence','east');
s=act(s,'answer','photo','1');assert.equal(s.answers.photo,undefined);assert.equal(s.question,'photo');
s=act(s,'answer','photo','2');assert.equal(s.answers.photo,true);assert.equal(s.complete,false);
s=act(s,'inspect','photo-back');assert.equal(s.seen.backRead,true);assert.equal(s.complete,false);
s=R.initial(JSON.parse(JSON.stringify(s)));
s=R.act(s,{type:'inspect',target:'photo-detail'});assert.equal(s.complete,false);
s=drain(s);assert.equal(s.complete,false);assert.equal(s.room,'weather');
assert.deepEqual(R.initial({version:2,complete:true}).seen,{});
console.log('2편 v3 관찰 선행조건·오답·도구 사용·대사 후 자동 이동·복원 통과');
let door=R.initial();door.room='prep';door.dialogue=[];
door=R.act(door,{type:'inspect',target:'door'});
assert.equal(door.seen.doorOpen,undefined,'문 열기 전에는 닫힌 그림 유지');
door=drain(door);assert.ok(!door.seen.doorOpen);
door=R.act(door,{type:'inspect',target:'door'});
assert.equal(door.after,'','열린 문을 다시 열지 않는다');
let hint=R.initial();hint.room='prep';hint.dialogue=[];hint.answers.wind=true;hint.seen.recovered=true;
hint=R.act(hint,{type:'inspect',target:'paper'});
assert.ok(!hint.dialogue.some(l=>/선택하고|눌러/.test(l.text)));
