const assert = require('node:assert/strict');
const H = require('./hana-search');
const C = require('./chapter2');
const run = (s, ...actions) => actions.reduce((v, a) => H.act(v, a), s);
const drain = s => { for (let i=0; i<30 && s.talk; i++) s=H.act(s,'next'); return s; };
let s=drain(H.initial());
assert.equal(s.found,false,'하나를 대사로 미리 발견하지 않는다');
assert.equal(H.act(s,'finish').complete,false,'조사 건너뛰기 방지');
s=H.act(s,'select-name');
s=H.act(s,'goal');
assert.equal(s.found,false,'물건 오사용으로 발견 조건을 건너뛰지 않는다');
s=drain(s);s=H.act(s,'stow');
s=H.act(s,'goal');s=drain(s);
assert.equal(s.heard,true);assert.equal(s.found,false);
s=drain(H.act(s,'approach'));
assert.equal(s.found,true);assert.equal(s.remembered,false);
s=drain(H.act(s,'eunho'));
assert.equal(s.remembered,false,'대화만으로 이름 종이 사용을 대체하지 않는다');
s=H.act(s,'select-name');s=H.act(s,'eunho');
assert.ok(s.talk);assert.equal(s.remembered,false,'이름과 공유 기억 대화를 끝까지 듣는다');
s=H.initial(JSON.parse(JSON.stringify(s)));
s=drain(s);assert.equal(s.remembered,true);
s=drain(H.act(s,'teacher'));assert.equal(H.act(s,'finish').complete,true);
let other=drain(H.initial());other=H.act(other,'camera');other=H.act(other,'take-note');
assert.equal(other.note,true);assert.equal(other.found,false);
other=drain(H.act(other,'goal'));other=drain(H.act(other,'approach'));
other=drain(H.act(H.act(other,'select-name'),'eunho'));
assert.equal(other.remembered,true,'선택 사물 조사 여부와 무관하게 합류');
assert.deepEqual(H.initial({selected:'invalid',found:'true'}).selected,'');
assert.equal(H.initial({remembered:true}).remembered,false,'깨진 저장의 선행 조건 복원');
const scenes=C.build();
let wind=drain(H.initial());
wind=H.act(wind,'cloth');
assert.equal(wind.detail,'wind');
wind=H.act(wind,'wind-left');
assert.equal(wind.windChecked,false);
assert.equal(wind.detail,'wind','오답 뒤 같은 장면에서 다시 예상');
wind=H.act(wind,'wind-right');
assert.equal(wind.windChecked,true);
assert.equal(H.initial(wind).windChecked,true);
assert.equal(wind.found,false,'바람 활동이 사람 발견을 대신하지 않는다');
let showing=drain(H.act(drain(H.act(drain(H.initial()),'goal')),'approach'));
showing=H.act(showing,'select-name');
assert.match(H.speech(showing)[1],/누구에게 보여/);
assert.match(H.speech(H.initial(showing))[1],/누구에게 보여/,'저장 복원 뒤에도 손에 든 종이 안내');
showing=H.act(showing,'hana');
assert.equal(showing.talk,'hanaName');
showing=drain(showing);
assert.equal(showing.selected,'name','하나에게 보여 준 뒤에도 종이를 들고 있다');
assert.equal(showing.remembered,false);
showing=drain(H.act(showing,'eunho'));
assert.equal(showing.remembered,true,'하나에게 먼저 보여 줘도 재선택 없이 진행');
assert.equal(scenes['chapter2-start'].next,'c2-search');
assert.equal(scenes['c2-search'].experiment,'hana-search');
assert.equal(scenes['c2-search'].next,'c2-teacher');
assert.ok(!scenes['chapter2-start'].line.includes('하나야!'));
assert.equal(C.restartFlags({'hana-search':s,oilSeparated:true})['hana-search'],undefined);
const fs=require('node:fs');
for(const file of ['room.js','hana-search-view.js']) assert.ok(fs.readFileSync(__dirname+'/'+file,'utf8').includes('RoomScene.render'),'1편과 같은 탐색 화면 생성기를 사용');
const R=require('./room-scene');
const html=R.render({place:'학교',goal:'골대',art:'assets/test.png',alt:'운동장',speaker:'소미',line:'<img onerror="bad">'});
assert.ok(html.includes('&lt;img'));
assert.ok(html.includes('data-room-action="bag"'));
assert.ok(html.includes('room-object-glow')===false,'윤곽은 각 장소 그림에 맞게 제공');
assert.ok(fs.existsSync(__dirname+'/assets/hana-first-meeting-v1.png'));
console.log('하나 탐색: 발견·물건 사용·오조작·대화·저장·재합류 통과');
