const assert=require('node:assert/strict');
const lab=require('./liquid-labs.js');
let o=lab.oilState();
assert.equal(lab.oilStep(o,'drain'),o);
o=lab.oilStep(o,'add-water');
o=lab.oilStep(o,'add-oil');
for(let i=0;i<5;i++)o=lab.oilStep(o,'drain');
assert.equal(o.water,0);assert.equal(o.cupWater,5);
const dirty=lab.oilStep(o,'drain');assert.equal(dirty.contaminated,true);
assert.equal(dirty.oil+dirty.cupOil,3);assert.equal(dirty.cupOil,1);
o=lab.oilStep(o,'switch');for(let i=0;i<3;i++)o=lab.oilStep(o,'drain');
assert.equal(lab.oilDone(o),true);assert.equal(o.cupOil,3);
assert.equal(lab.oilDone(dirty),false);
assert.deepEqual(lab.oilStep(dirty,'reset'),lab.oilState());
let s=lab.saltState();
for(const action of ['filter','heat','stir'])assert.equal(lab.saltStep(s,action),s);
for(const action of ['water','stir','filter','teacher','heat','heat','heat'])s=lab.saltStep(s,action);
assert.equal(s.phase,'done');assert.equal(s.salt,4);assert.equal(s.sand,6);assert.equal(s.water,0);
assert.equal(lab.saltStep(s,'heat'),s);
console.log('물·기름 오염·재시도·보존 / 소금·모래 순서·교사 가열·보존 통과');
