const assert = require('node:assert/strict');
const room = require('./room.js');
let prep=room.initial('supplies');
assert.equal(room.step(prep,'wrap').wrapped,false);
prep=room.step(prep,'weigh-right');prep=room.step(prep,'apparatus-right');
assert.equal(prep.massChecked&&prep.filterChecked,true);
assert.deepEqual(room.restore('supplies',prep),prep);
let floor=room.initial('finale');
for(const id of ['floorPaper','floorTape','floorBox']){
 floor=room.step(floor,id);
 assert.equal(floor[id],true,'바닥 소품 조사 기록 저장');
}
assert.equal(floor.route,false,'바닥 조사만으로 본래 추리를 건너뛰지 않음');
assert.deepEqual(room.restore('finale',floor),floor);
let s = room.initial('supplies');
assert.equal(room.step(s,'drawer').complete,false);
s=room.step(s,'tray');
assert.equal(room.step(s,'sieve-wrong').key,false);
s=room.step(s,'sieve-right');
assert.equal(s.key,true);
assert.equal(room.step(s,'drawer').complete,false,'소지품을 선택해야 사용 가능');
s=room.step(s,'select-key');
s=room.step(s,'drawer');
assert.equal(s.complete,false,'서랍 개방만으로 도구 수집 완료 금지');
assert.equal(room.step(s,'tools-wrong').complete,false);
s=room.step(s,'tools-right');
assert.equal(s.complete,true);
s=room.initial('finale');
assert.equal(room.step(s,'door').complete,false);
assert.equal(room.step(s,'play').heard,false);
s=room.step(s,'select-key'); s=room.step(s,'drawer');
assert.equal(s.tape,false,'원고 보관 규칙을 확인해야 테이프 획득');
s=room.step(s,'tape-right');
assert.equal(s.tape,true);
assert.equal(room.step(s,'play').heard,false,'원고와 장치를 복구해야 재생');
assert.equal(room.step(s,'script-right').script,false,'게시판 조사 선행');
s=room.step(s,'board'); s=room.step(s,'script-wrong');
assert.equal(s.script,false);
s=room.step(s,'script-right');
s=room.step(s,'equipment'); s=room.step(s,'device-right');
assert.equal(s.power,false,'선택 이유까지 필요');
s=room.step(s,'reason-right');
assert.equal(s.power,true);
s=room.step(s,'select-tape'); s=room.step(s,'tv');
assert.equal(s.loaded,true);
assert.equal(room.step(s,'play').heard,false,'촬영 기록을 연결하기 전 방송 순서 확인 필요');
assert.equal(room.step(s,'route-right').route,false,'증거 없이 추리 완료 금지');
for(const clue of ['notebook','cases','camera'])s=room.step(s,clue);
assert.equal(room.step(s,'route-wrong').route,false);
s=room.step(s,'route-right');assert.equal(s.route,true);
s=room.step(s,'play'); assert.equal(s.heard,true);
assert.equal(room.step(s,'code-wrong').unlocked,false);
s=room.step(s,'code-right'); assert.equal(s.unlocked,true);
assert.equal(room.step(s,'door').complete,true);
assert.deepEqual(room.restore('finale',JSON.parse(JSON.stringify(s))),s);
assert.equal(room.restore('supplies',s).complete,false,'다른 구간 저장 무시');
console.log('방 탐색: 아이템 사용·선행 단서·학습 근거·재생·탈출·저장 통과');
